[project]
name = "reshape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["click>=8.3.1", "xxhash>=3.6.0"]


[tool.uv]
package = true

[project.scripts]
reshape = "reshape.__main__:reshape"
